name: ci
on:
  push:
   branches:
     - docker
jobs:
  dockerfile:
    env:
      project: santander-phpinfo
      user: barsanse
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: docker build --file Dockerfile --no-cache --tag index.docker.io/${user}/${project}:ci .
      - name: run
        run: docker run --detach --name ${project} index.docker.io/${user}/${project}:ci
      - name: test
        run: while true ; do sleep 10 ; docker logs ${project} 2>& 1 | grep started && break ; done
      - name: top
        run: docker top ${project}
      - name: stats
        run: docker stats --no-stream ${project}
      - name: inspect
        run: docker inspect ${project}
      - name: history
        run: docker history index.docker.io/${user}/${project}:ci
